import cover1 from "../images/cover1.png";
import cover2 from "../images/cover2.jpg";
import cover3 from "../images/cover3.jpg";
import cover4 from "../images/cover4.jpg";
import cover5 from "../images/cover5.jpg";
import cover6 from "../images/cover6.jpg";
import cover7 from "../images/cover7.jpg";
import cover8 from "../images/cover8.jpg";
import cover9 from "../images/cover9.jpg";
import cover10 from "../images/cover10.jpg";
import cover11 from "../images/cover11.jpg";
import cover12 from "../images/cover12.jpg";

import profile1 from "../images/profile_img/profile1.png";

export const data = [
  {
    post_id: 1,
    cover: [cover1, cover2, cover3],
    title: "먹태깡 팝니다",
    price: 1000,
    place: "진주시",
    attention: 11,
    chatting: 13,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 36,
    content: "내용1",
  },
  {
    post_id: 2,
    cover: cover2,
    title: "저와 함께하는 기린 인형",
    price: 12000,
    place: "서대문구",
    attention: 21,
    chatting: 17,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 38,
    content: "내용1",
  },
  {
    post_id: 3,
    cover: cover3,
    title: "눈여겨보고 있는 보조배터리",
    price: 1500,
    place: "통영시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 42,
    content: "내용1",
  },
  {
    post_id: 4,
    cover: cover4,
    title: "티셔츠 팝니다",
    price: 1500,
    place: "통영시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 50,
    content: "내용1",
  },
  {
    post_id: 5,
    cover: cover5,
    title: "무료나눔합니다",
    price: 1500,
    place: "제주시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 100,
    content: "내용1",
  },
  {
    post_id: 6,
    cover: cover6,
    title: "표지 이쁜 책 팔아요",
    price: 1500,
    place: "통영시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용1",
  },
  {
    post_id: 7,
    cover: cover7,
    title: "헤어 앰플이어요",
    price: 1500,
    place: "통영시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용7",
  },
  {
    post_id: 8,
    cover: cover8,
    title: "뭔가를 팝니다",
    price: 1500,
    place: "통영시",
    attention: 13,
    chatting: 16,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용1",
  },
  {
    post_id: 9,
    cover: cover9,
    title: "귀여운 팅클이 인형 소개합니다",
    price: 5000,
    place: "울산시",
    attention: 52,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용9",
  },
  {
    post_id: 10,
    cover: cover10,
    title: "많이 못해서 아쉬워요",
    price: 15000,
    place: "성주시",
    attention: 2,
    chatting: 1,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용1",
  },
  {
    post_id: 11,
    cover: cover11,
    title: "하지만 프론트 최고 프론트 짱",
    price: 5000,
    place: "울산시",
    attention: 52,
    chatting: 91,
    username: "ㅎㅎ",
    profile: profile1,
    temp: 33,
    content: "내용11",
  },
  {
    post_id: 12,
    cover: cover12,
    title: "최근의 고양이 행운 공유합니다",
    price: 15000,
    place: "이대 멋사 짱 프론트 ♥️",
    attention: 2000,
    chatting: 16000,
    username: "ㅎㅎg",
    profile: profile1,
    temp: 39,
    content: "내용12",
  },
];
